# MkDocs configuration for  builds with Material theme

site_name: Percona Ivee
site_description: Documentation
site_author: Percona LLC
copyright:  <a href="https://www.percona.com/about">Percona LLC</a> and/or its affiliates © 2024 — <a href="#__consent">Cookie Consent</a>

repo_name: percona/ivee-docs

repo_url: https://github.com/percona/ivee-docs
edit_uri: edit/main/docs/

use_directory_urls: false

# Material theme features
theme:
  name: material
  logo: _images/percona-mark.svg
  favicon: _images/percona-fav.svg
  custom_dir: _resource/overrides/
  font:
    text: Roboto  
    code: Roboto Mono
  icon:
    edit: material/file-edit-outline
    view: material/file-eye-outline

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Color theme set to Automatic. Click to change
    - media: "(prefers-color-scheme: light)"
      scheme: percona-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Color theme set to Light Mode. Click to change
    - media: "(prefers-color-scheme: dark)"
      scheme: percona-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Color theme set to Dark Mode. Click to change

# Theme features

  features:
    - search.highlight
    - navigation.top
    - navigation.tracking 
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy  

extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  - css/extra.css
  - css/design.css
  - css/osano.css
  - css/landing.css

extra_javascript:
  - js/promptremover.js
  - js/consent.css

markdown_extensions:
  attr_list: {}
  toc:
    permalink: True
    title: On this page
  admonition: {}
  footnotes: {}
  def_list: {} # https://michelf.ca/projects/php-markdown/extra/#def-list
  meta: {}
  md_in_html: {}
  smarty:
      {smart_angled_quotes: true}
  pymdownx.details: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.tabbed: 
      {alternate_style: true}
  pymdownx.tilde: {}
  pymdownx.superfences: 
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.highlight:
      use_pygments: true
  pymdownx.inlinehilite: {}
  pymdownx.snippets:
      base_path: ["snippets"]
#      auto_append:
#        - feedback-banner.md
  pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - _resource/.icons


plugins:
  section-index: {}
  search: 
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  git-revision-date-localized: 
    enable_creation_date: true
    enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
  meta-descriptions:
    export_csv: false
    quiet: false
    enable_checks: false
    min_length: 50
    max_length: 160
  macros:
      include_yaml:
        - 'variables.yml' # Use in markdown as '{{ VAR }}'
# exclude: # Don't process these files
#      glob:
#         - file.md
#  with-pdf: # https://github.com/orzih/mkdocs-with-pdf
#          output_path: '_pdf/PerconaDistributionPostgreSQL-16.pdf'
#          cover_title: 'Distribution for PostgreSQL Documentation'#

#          cover_subtitle: 16.3 (June 6, 2024)
#          author: 'Percona Technical Documentation Team'
#          cover_logo: docs/_images/Percona_Logo_Color.png
#          debug_html: false
#          custom_template_path: _resource/templates
#          enabled_if_env: ENABLE_PDF_EXPORT
#  mike:
#      version_selector: true
#      css_dir: css
#      javascript_dir: js
#      canonical_version: null#

#extra:
#  version:
#    provider: mike
#  #homepage:
#  #  https://docs.percona.com
#  postgresrecommended: 16

#Google Analytics configuration 
extra:
  analytics:
    provider: google
    property: G-J4J70BNH0G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thank you for your feedback! Help us improve by following this <a href="https://docs.google.com/forms/d/1bkWACehjqlwA0AKf-qTJcXvYbOSYgze8iTPXjntqmNo/edit" target="_blank" rel="noopener">feedback form</a>.

nav:
  - Home: index.md
  - get-help.md
  - Getting started:
      - Quickstart: quickstart.md
      - Beta program: beta-program.md
      - Free Tier: free-tier.md
  - Features:
    - features/features.md
    - Backups: 
      - features/backups.md
    - Autoscaling and serverless: 
      - features/autoscaling.md
    - Deployment modes:
      - Public DBaaS: 
        - deploy/mode-public.md
      - Bring your own account: 
        - deploy/mode-byoa.md
  - Services:
    - PostgreSQL: 
      - services/postgresql.md 
      - For AI:
        - services/postgresql-for-ai.md
    - Valkey: 
      - services/valkey.md
      - Connect to Valkey:
        - services/valkey-connect.md
    - MySQL: services/mysql.md
    - FerretDB: services/ferretdb.md
    - Percona Monitoring and Management: services/pmm.md

      
